---
project_name: gherkin-lingo

release:
  github:
    owner: remast
    name: gherkin-lingo

brew:
  skip_upload: true
  description: Linter for Gherkin files.

builds:
  - binary: gherkin-lingo
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - i386
    env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archive:
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
    - README*
